# -*- coding: utf-8 -*-
"""Titanic(RF).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mdpf3viLaTgSRmbkDPQkdVoZK3ShtlAx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.tree import plot_tree

# Download the dataset
print("Downloading dataset...")
path = kagglehub.dataset_download("dwiuzila/titanic-machine-learning-from-disaster")
print("Path to dataset files:", path)

# Load the CSV file (Adjusting path based on your previous code)
# Note: We usually train on 'train.csv', but based on your file, we look for the file with 'Survived' column.
# Let's try loading the specific file you referenced.
csv_path = f"{path}/test.csv"
try:
    df = pd.read_csv(csv_path)
    print("Data loaded successfully.")
except FileNotFoundError:
    # Fallback if file name differs
    import os
    files = os.listdir(path)
    csv_path = os.path.join(path, files[0])
    df = pd.read_csv(csv_path)
    print(f"Loaded {files[0]} instead.")

df.head()

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df = df.drop(['Cabin', 'Name', 'Ticket', 'PassengerId'], axis=1)
df = df.dropna(subset=['Embarked'])
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)
print(df)
print("Data is now clean and numeric:")
df.head()

X = df.drop('Survived', axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(n_estimators=100, max_depth=4, random_state=42)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print("Model Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(24, 12), dpi=100)
for index in range(4):
    row = index // 2
    col = index % 2

    # Plot the specific tree
    plot_tree(rf_model.estimators_[index],
              feature_names=X.columns,
              class_names=['Deceased', 'Survived'],
              filled=True,
              rounded=True,
              fontsize=9,
              max_depth=3,
              ax=axes[row, col])
    axes[row, col]

plt.tight_layout()
plt.show()

